### ISSUE TITLE
Cannot send emails after upgrading to v3

### ISSUE THREAD

**Issue by amplitudesxd** [postalserver/postal#2843]
## Describe the bug

After upgrading to Postal v3 and attempting to send an email, the following error is produced: `NameError: undefined local variable or method `hosts' for SMTPSender:Class`

## To Reproduce

1. Upgrade to Postal v3 from v2
2. Attempt to send an email
3. See error

## Additional information/context

```
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   internal error: NameError: undefined local variable or method `hosts' for SMTPSender:Class component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/senders/smtp_sender.rb:253:in `smtp_relays' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/senders/smtp_sender.rb:28:in `start' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/state.rb:12:in `sender_for' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/outgoing_message_processor.rb:138:in `send_message_to_sender' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/outgoing_message_processor.rb:20:in `block in process' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/base.rb:38:in `catch_stops' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/outgoing_message_processor.rb:7:in `process' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/base.rb:26:in `process' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/single_message_processor.rb:25:in `block in process' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/base.rb:38:in `catch_stops' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/single_message_processor.rb:7:in `process' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/base.rb:26:in `process' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/initial_processor.rb:57:in `block in process_message' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /usr/local/bundle/gems/klogger-logger-1.4.0/lib/klogger/group_set.rb:18:in `call_without_id' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /usr/local/bundle/gems/klogger-logger-1.4.0/lib/klogger/logger.rb:72:in `tagged' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/initial_processor.rb:56:in `process_message' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/initial_processor.rb:19:in `block (2 levels) in process' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/base.rb:38:in `catch_stops' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/initial_processor.rb:12:in `block in process' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /usr/local/bundle/gems/klogger-logger-1.4.0/lib/klogger/group_set.rb:18:in `call_without_id' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /usr/local/bundle/gems/klogger-logger-1.4.0/lib/klogger/logger.rb:72:in `tagged' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer/initial_processor.rb:9:in `process' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/message_dequeuer.rb:9:in `process' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/jobs/process_queued_messages_job.rb:67:in `block in process_messages' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/relation/delegation.rb:88:in `each' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/relation/delegation.rb:88:in `each' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/jobs/process_queued_messages_job.rb:65:in `process_messages' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/jobs/process_queued_messages_job.rb:14:in `call' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/process.rb:143:in `block (4 levels) in work' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /usr/local/lib/ruby/3.2.0/benchmark.rb:311:in `realtime' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/process.rb:143:in `block (3 levels) in work' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/process.rb:264:in `capture_errors' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/process.rb:140:in `block (2 levels) in work' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/process.rb:139:in `each' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/process.rb:139:in `block in work' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /usr/local/bundle/gems/activerecord-7.0.8.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:215:in `with_connection' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/process.rb:138:in `work' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/process.rb:121:in `block (3 levels) in start_work_thread' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/process.rb:120:in `loop' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/process.rb:120:in `block (2 levels) in start_work_thread' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /usr/local/bundle/gems/klogger-logger-1.4.0/lib/klogger/group_set.rb:18:in `call_without_id' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /usr/local/bundle/gems/klogger-logger-1.4.0/lib/klogger/logger.rb:72:in `tagged' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   /opt/postal/app/app/lib/worker/process.rb:118:in `block in start_work_thread' component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   message requeued for trying later, at 2024-03-05 18:41:08 UTC component=worker thread=work0 original_queued_message=68799 queued_message=68799
postal-worker-1  | 2024-03-05 18:34:38 +0000 INFO   finished message unqueue component=worker thread=work0 original_queued_message=68799
```

**Comment by arnebr** [comment]
Can reproduce that error with the same error message:
`NameError: undefined local variable or method `hosts' for SMTPSender:Class`

**Comment by adamcooke** [comment]
This is fixed and will be released in 3.0.1 shortly.
