### ISSUE TITLE
500 error on login - undefined method "login_ip_country", when accessing webserver through reverse proxy

### ISSUE THREAD

**Issue by jjgmckenzie** [postalserver/postal#3057]
## Describe the bug

500 error when logging in to web mailserver behind traefik reverse proxy.

## To Reproduce

1. Set up reverse proxy for webserver.
2. Using webserver, attempt to login
3. Reverse Proxy uses a private IP, so has no country attributed. 
4. Receive error "undefined method `login_ip_country=' for #<Authie::SessionModel" -- full error msg below

## Expected behaviour

No 500 error. This is a bug after upgrading to v3. Postal should respect the forwarded-for header when logging access, especially when considering many users of cloudflare / reverse proxies.

## Additional information/context

```
2024-07-25 21:28:54 +0000 ERROR  POST /login (500) event=request transaction=eba300332dfca1adfd72 controller=SessionsController action=create format=html method=POST path=/login request_id=6a51a265-b6ad-4d02-9257-ffb70df03ee9 ip_address=172.18.0.3 status=500 db_runtime=49.19976091384888 exception_class=NoMethodError exception_message=undefined method `login_ip_country=' for #<Authie::SessionModel id: nil, token: nil, browser_id: "2260e227-4a44-4043-93d6-84026d2a6db4", user_id: 1, active: true, data: nil, expires_at: nil, login_at: "2024-07-25 21:28:54.000000000 +0000", login_ip: "172.18.0.3", last_activity_at: nil, last_activity_ip: nil, last_activity_path: nil, user_agent: nil, created_at: nil, updated_at: nil, user_type: "User", parent_id: nil, two_factored_at: nil, two_factored_ip: nil, requests: 0, password_seen_at: nil, token_hash: nil, host: nil> exception_backtrace=/usr/local/bundle/gems/activemodel-7.0.8.1/lib/active_model/attribute_methods.rb:450:in `method_missing'\n/usr/local/bundle/gems/authie-4.1.3/lib/authie/session.rb:252:in `start'\n/usr/local/bundle/gems/authie-4.1.3/lib/authie/controller_delegate.rb:82:in `create_auth_session'\n/usr/local/bundle/gems/authie-4.1.3/lib/authie/controller_extension.rb:18:in `create_auth_session'
```

**Comment by jjgmckenzie** [comment]
My bad. Failed to update correctly using postal update when upgrading.
